services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: coachtech_app
    volumes:
      - ./:/var/www/html
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - coachtech_network
    environment:
      - DB_HOST=db
      - DB_DATABASE=coachtech
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - DB_CONNECTION=mysql
    command: php artisan serve --host=0.0.0.0 --port=8000

  db:
    image: mysql:8.0
    container_name: coachtech_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: coachtech
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d:ro
    networks:
      - coachtech_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: coachtech_phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - db
    networks:
      - coachtech_network

networks:
  coachtech_network:
    driver: bridge

volumes:
  db_data:
